paths:
  data: data
  uploads: static/images
collections_config:
  pages:
    path: content
    output: true
    filter: strict
    parse_branch_index: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  data:
    path: data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
data_config: true
timezone: Etc/UTC
