# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Button"
  description:
  icon: smart_button
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  link: "/"
  text: "Hello World!"
  background_color: "transparent"
  color: "black"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  background_color:
    type: select
    label: Background Color
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: label
  color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: label
  link:
    type: url

