# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: 'Six Column Grid'
  description: 'A grid of six cards, each with a link, text, and background image.'
  icon: view_comfy
  tags:
    - Grid

# Defines the structure of this component, as well as the default values
blueprint:
  height: 320
  cards:
    - link: /en-US/game/wwe-2k24/
      text: 'WWE 2K24'
      background_image: https://cdn.2kgames.com/2024/03/08/65eb8286bef0fWWE24-WEBSITE-2K_ASSET600X600.jpg
      background_color: '#CC0001'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  height:
    type: number
    comment: The height of the grid.
  cards:
    type: array
  cards[*]:
    type: object
    options:
      preview:
        icon: image
        image:
          - key: background_image
        text:
          - key: text
          - 'Grid Item'
        subtext:
          - key: link
  link:
    type: url
  background_color:
    hidden: 'background_image'
