# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: 'Hero - Slideshow'
  description: 'A hero slideshow'
  icon: slideshow
  tags:
    - Hero
    - Slideshow

# Defines the structure of this component, as well as the default values
blueprint:
  slide_time: 5000
  slides:
    - background_image: https://cdn.2kgames.com/2023/08/23/64e68baae75e2NBA2K24_keyart.jpg
      heading: NBA 2K24
      subheading: SEE YOU ON THE COURT
      logo:
        src: https://cdn.2kgames.com/2023/08/24/64e7c7049954c2k24-logo.jpg
        max_width: 450
        margin_top: 0
        margin_bottom: 10
      link: https://nba.2k.com/2k24/
      primary_button: bookshop:button
      secondary_button: bookshop:button
    - background_image: https://cdn.2kgames.com/2023/10/09/6524129aa7afcNBA-Mobile-Marquee-KM.jpg
      heading: NBA 2K24
      subheading: SEE YOU ON THE COURT
      logo:
        src: https://cdn.2kgames.com/2023/08/24/64e7c7049954c2k24-logo.jpg
        max_width: 450
        margin_top: 0
        margin_bottom: 10
      link: https://nba.2k.com/2k24/
      primary_button: bookshop:button
      secondary_button: bookshop:button

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  src:
    label: Image Source
    type: image
  max_width:
    type: number
  margin_top:
    type: number
  margin_bottom:
    type: number
  link:
    type: url
  slide_time:
    type: number
    comment: 'Time in milliseconds for each slide to be displayed. This will only take effect when the page is saved, and refreshed.'
  slides:
    type: array
  slides[*]:
    type: object
    options:
      preview:
        image:
          - key: background_image
        text:
          - key: heading
          - 'Slide'
        subtext:
          - key: subheading
        icon: slideshow
