# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: 'Three Column Grid'
  description: 'A grid of three cards, each with a link, text, and background image.'
  icon: view_module
  tags:
    - Grid

# Defines the structure of this component, as well as the default values
blueprint:
  height: 320
  cards:
    - link: /en-US/game/wwe-2k24/
      text: 'WWE 2K24'
      background_image:
        src: https://cdn.2kgames.com/2024/03/08/65eb8286bef0fWWE24-WEBSITE-2K_ASSET600X600.jpg
        brightness: 0.8
        background_color: '#CC0001'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  height:
    type: number
  cards:
    type: array
  cards[*]:
    type: object
    options:
      preview:
        image:
          - key: background_image.src
        text:
          - key: text
          - 'Grid Item'
        subtext:
          - key: link
        icon: image
  link:
    type: url
  background_color:
    hidden: 'src'
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: label
  background_image:
    label: Background Image
    type: object
    options:
      preview:
        gallery:
          image:
            - key: src
          icon: image
  src:
    label: Image Source
    type: image
  brightness:
    type: number
    options:
      min: 0
      max: 2
      step: 0.01
  text:
    type: textarea
